/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const XIconAppStore: typeof import('~icons/icon/app-store.jsx')['default']
  const XIconArrowRight: typeof import('~icons/icon/arrow-right.jsx')['default']
  const XIconCheck: typeof import('~icons/icon/check.jsx')['default']
  const XIconClose: typeof import('~icons/icon/close.jsx')['default']
  const XIconCopied: typeof import('~icons/icon/copied.jsx')['default']
  const XIconCopy: typeof import('~icons/icon/copy.jsx')['default']
  const XIconDarkMode: typeof import('~icons/icon/dark-mode.jsx')['default']
  const XIconDiscord: typeof import('~icons/icon/discord.jsx')['default']
  const XIconDown: typeof import('~icons/icon/down.jsx')['default']
  const XIconGithub: typeof import('~icons/icon/github.jsx')['default']
  const XIconGithubFilled: typeof import('~icons/icon/github-filled.jsx')['default']
  const XIconGoogleColorful: typeof import('~icons/icon/google-colorful.jsx')['default']
  const XIconKey: typeof import('~icons/icon/key.jsx')['default']
  const XIconLightMode: typeof import('~icons/icon/light-mode.jsx')['default']
  const XIconLove: typeof import('~icons/icon/love.jsx')['default']
  const XIconTwitterColorful: typeof import('~icons/icon/twitter-colorful.jsx')['default']
}
