/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const XIconCheck: typeof import('~icons/icon/check.jsx')['default']
  const XIconClose: typeof import('~icons/icon/close.jsx')['default']
  const XIconDarkMode: typeof import('~icons/icon/dark-mode.jsx')['default']
  const XIconDown: typeof import('~icons/icon/down.jsx')['default']
  const XIconGithub: typeof import('~icons/icon/github.jsx')['default']
  const XIconKey: typeof import('~icons/icon/key.jsx')['default']
  const XIconLightMode: typeof import('~icons/icon/light-mode.jsx')['default']
  const XIconLove: typeof import('~icons/icon/love.jsx')['default']
}
