/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const XIconDarkMode: typeof import('~icons/icon/dark-mode.jsx')['default']
  const XIconGithub: typeof import('~icons/icon/github.jsx')['default']
  const XIconLightMode: typeof import('~icons/icon/light-mode.jsx')['default']
  const XIconLove: typeof import('~icons/icon/love.jsx')['default']
}
