# 一个 workflow，名为 Deploy

name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build-and-deploy: # 构建 job
    runs-on: ubuntu-latest # 跑 workflow 的服务器系统
    steps: # job的一系列动作 
      # 切换分支获取源码
      - name: Checkout # step的名称，将会在 github action 的控制台中显示
        uses: actions/checkout@v3 # 选择一个action，可以理解为若干 steps.run，有利于代码复用

      # 安装使用 node:14.18.0
      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.19.0 # node版本

      # 运行命令，npm install
      - name: Install
        run: |
          node -v
          npm install -g pnpm
          pnpm i

      # 运行命令，npm run build
      - name: Build
        run: pnpm build

      - name: Debug
        run: |
          ls ${{ secrets.BUILD_DIST }} 
          echo ${{ secrets.SERVER_SSH_TARGET }}

      # 部署到腾讯云服务器
      - name: Upload files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_SSH_HOST }} # 服务器域名
          username: ${{ secrets.SERVER_SSH_USER }} # 腾讯云默认用户名为root
          key: ${{ secrets.SERVER_SSH_KEY }} # 本地.ssh文件下的私钥id_rsa，存在secrets中
          source: ${{ secrets.BUILD_DIST }} # 源目录，相对于$GITHUB_WORKSPACE根目录的路径
          target: ${{ secrets.SERVER_SSH_TARGET }} # 目标目录
